runtime: python37

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
  - url: /api
    script: auto
  - url: /.*
    script: auto
